### ISSUE TITLE
播放被删除缓存文件

### ISSUE THREAD

**Issue by mayemonkey** [easefun/polyv-android-sdk-2.0-demo#10]
本地文件被删除后，在断网情况下，videoView调用setVid设置isFromLocal为true进行播放，sdk内部抛出异常崩溃。
`java.lang.ExceptionInInitializerError
                                                               at com.easefun.polyvsdk.log.PolyvLogFile.extractLogcat2File(PolyvLogFile.java:79)
                                                               at com.easefun.polyvsdk.video.PolyvVideoViewListenerEvent.callOnVideoPlayErrorListener(PolyvVideoViewListenerEvent.java:412)
                                                               at com.easefun.polyvsdk.video.PolyvVideoView.callOnVideoPlayErrorListener(PolyvVideoView.java:2795)
                                                               at com.easefun.polyvsdk.video.PolyvVideoView.callOnVideoPlayErrorListener(PolyvVideoView.java:2790)
                                                               at com.easefun.polyvsdk.video.PolyvVideoView.callOnVideoPlayErrorListener(PolyvVideoView.java:2785)
                                                               at com.easefun.polyvsdk.video.PolyvVideoView$14.run(PolyvVideoView.java:906)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                               at java.lang.Thread.run(Thread.java:764)
                                                            Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                               at android.os.Handler.<init>(Handler.java:203)
                                                               at android.os.Handler.<init>(Handler.java:117)
                                                               at com.easefun.polyvsdk.log.a.<init>(PolyvELogStore.java:577)
                                                               at com.easefun.polyvsdk.log.PolyvELogStore.<init>(PolyvELogStore.java:39)
                                                               at com.easefun.polyvsdk.log.PolyvLogFile.<clinit>(PolyvLogFile.java:42)
                                                               at com.easefun.polyvsdk.log.PolyvLogFile.extractLogcat2File(PolyvLogFile.java:79) 
                                                               at com.easefun.polyvsdk.video.PolyvVideoViewListenerEvent.callOnVideoPlayErrorListener(PolyvVideoViewListenerEvent.java:412) 
                                                               at com.easefun.polyvsdk.video.PolyvVideoView.callOnVideoPlayErrorListener(PolyvVideoView.java:2795) 
                                                               at com.easefun.polyvsdk.video.PolyvVideoView.callOnVideoPlayErrorListener(PolyvVideoView.java:2790) 
                                                               at com.easefun.polyvsdk.video.PolyvVideoView.callOnVideoPlayErrorListener(PolyvVideoView.java:2785) 
                                                               at com.easefun.polyvsdk.video.PolyvVideoView$14.run(PolyvVideoView.java:906) 
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                               at java.lang.Thread.run(Thread.java:764)`

**Comment by mayemonkey** [comment]
更换过时初始化已不会抛出异常
`PolyvSDKClient client = PolyvSDKClient.getInstance();
//初始化数据库服务
client.initSetting(getApplicationContext());

//过时设置
//client.initDatabaseService(this);
//client.startService(getApplicationContext(), PolyvService.class);`
